language: node_js
node_js:
  - "node"
notifications:
  email: false
cache:
  directories:
    - node_modules
before_install:
  - npm install -g npm-install-peers && npm-install-peers
script:
  - npm test
  - npm run lint
  - npm run build
